# = = = = = PDF = = = = =

gpi_run-texlive-docker:
	cd src/gpi_texlive-full; docker-compose up
	cd src/gpi_texlive-full; docker-compose down

gpi_clean-texlive:
	cd src/gpi_texlive-full; make gpi_clean
